name: Release internal
on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  release-internal:
    name: Release internal
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version-file: .github/workflows/.java-version
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Release internal
        run: ./gradlew publishAllPublicationsToInternalRepository -DRELEASE_SIGNING_ENABLED=false
        env:
          ORG_GRADLE_PROJECT_internalUrl: https://maven.pkg.github.com/jakubmeysner/wire
          ORG_GRADLE_PROJECT_internalUsername: ${{ github.actor }}
          ORG_GRADLE_PROJECT_internalPassword: ${{ github.token }}
